---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - prism-ctf.pwnlentoni.team
  resources:
  - sharedchallenges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prism-ctf.pwnlentoni.team
  resources:
  - sharedchallenges/finalizers
  verbs:
  - update
- apiGroups:
  - prism-ctf.pwnlentoni.team
  resources:
  - sharedchallenges/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: prism-ctf-challenges
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  - ingresses
  - ingressroutes
  - ingressroutetcps
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
