---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - ciliumnetworkpolicies
  - configmaps
  - deployments
  - httproutes
  - namespaces
  - services
  - tlsroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - prism-ctf.pwnlentoni.team
  resources:
  - challengeinstances
  - sharedchallenges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prism-ctf.pwnlentoni.team
  resources:
  - challengeinstances/finalizers
  - sharedchallenges/finalizers
  verbs:
  - update
- apiGroups:
  - prism-ctf.pwnlentoni.team
  resources:
  - challengeinstances/status
  - sharedchallenges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - prism-ctf.pwnlentoni.team
  resources:
  - isolatedchallenges
  verbs:
  - get
  - list
  - watch
