## Append samples of your project ##
resources:
- prism-ctf_v1_sharedchallenge_http.yaml
- prism-ctf_v1_sharedchallenge_tcp.yaml
- prism-ctf_v1_isolatedchallenge_http.yaml
- prism-ctf_v1_challengeinstance.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
