apiVersion: prism-ctf.pwnlentoni.team/v1
kind: PrismServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: prism-ctf
    app.kubernetes.io/managed-by: kustomize
  name: prismserviceaccount-sample
spec:
  # TODO(user): Add fields here
