resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: placeholder-http
  newName: registry.gitlab.com/pwnlentoni/prism-ctf/placeholder-http
  newTag: latest
- name: placeholder-tcp
  newName: registry.gitlab.com/pwnlentoni/prism-ctf/placeholder-tcp
  newTag: latest
